#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("App1.Resource", IsApplication=true)]

namespace App1
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010006
			public const int beep_on_result = 2130771974;
			
			// aapt resource value: 0x7f010008
			public const int blink_animation_on_result = 2130771976;
			
			// aapt resource value: 0x7f010030
			public const int camera_id = 2130772016;
			
			// aapt resource value: 0x7f010009
			public const int cancel_on_result = 2130771977;
			
			// aapt resource value: 0x7f010013
			public const int crop_gravity = 2130771987;
			
			// aapt resource value: 0x7f010018
			public const int cutout_alignment = 2130771992;
			
			// aapt resource value: 0x7f010027
			public const int cutout_crop_offset_x = 2130772007;
			
			// aapt resource value: 0x7f010028
			public const int cutout_crop_offset_y = 2130772008;
			
			// aapt resource value: 0x7f010025
			public const int cutout_crop_padding_x = 2130772005;
			
			// aapt resource value: 0x7f010026
			public const int cutout_crop_padding_y = 2130772006;
			
			// aapt resource value: 0x7f010024
			public const int cutout_drawable = 2130772004;
			
			// aapt resource value: 0x7f01000a
			public const int cutout_feedback_stroke_color = 2130771978;
			
			// aapt resource value: 0x7f01001b
			public const int cutout_max_height_percent = 2130771995;
			
			// aapt resource value: 0x7f01001a
			public const int cutout_max_width_percent = 2130771994;
			
			// aapt resource value: 0x7f01001c
			public const int cutout_offset_x = 2130771996;
			
			// aapt resource value: 0x7f01001d
			public const int cutout_offset_y = 2130771997;
			
			// aapt resource value: 0x7f010029
			public const int cutout_outside_color = 2130772009;
			
			// aapt resource value: 0x7f010022
			public const int cutout_ratio_from_size_height = 2130772002;
			
			// aapt resource value: 0x7f010021
			public const int cutout_ratio_from_size_width = 2130772001;
			
			// aapt resource value: 0x7f010023
			public const int cutout_rect_corner_radius_in_dp = 2130772003;
			
			// aapt resource value: 0x7f010020
			public const int cutout_stroke_color = 2130772000;
			
			// aapt resource value: 0x7f01001f
			public const int cutout_stroke_width_in_dp = 2130771999;
			
			// aapt resource value: 0x7f01001e
			public const int cutout_style = 2130771998;
			
			// aapt resource value: 0x7f010019
			public const int cutout_width = 2130771993;
			
			// aapt resource value: 0x7f01002b
			public const int flash_alignment = 2130772011;
			
			// aapt resource value: 0x7f01002e
			public const int flash_image_auto = 2130772014;
			
			// aapt resource value: 0x7f01002d
			public const int flash_image_off = 2130772013;
			
			// aapt resource value: 0x7f01002c
			public const int flash_image_on = 2130772012;
			
			// aapt resource value: 0x7f01002a
			public const int flash_mode = 2130772010;
			
			// aapt resource value: 0x7f010000
			public const int overlay_drawable = 2130771968;
			
			// aapt resource value: 0x7f010015
			public const int overlay_height = 2130771989;
			
			// aapt resource value: 0x7f010001
			public const int overlay_outside_color = 2130771969;
			
			// aapt resource value: 0x7f010014
			public const int overlay_width = 2130771988;
			
			// aapt resource value: 0x7f010016
			public const int overlay_x = 2130771990;
			
			// aapt resource value: 0x7f010017
			public const int overlay_y = 2130771991;
			
			// aapt resource value: 0x7f010002
			public const int preferred_picture_height = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int preferred_picture_width = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int preferred_preview_height = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int preferred_preview_width = 2130771973;
			
			// aapt resource value: 0x7f01002f
			public const int show_fps = 2130772015;
			
			// aapt resource value: 0x7f010007
			public const int vibrate_on_result = 2130771975;
			
			// aapt resource value: 0x7f010011
			public const int visual_feedback_animation_duration = 2130771985;
			
			// aapt resource value: 0x7f010010
			public const int visual_feedback_animation_style = 2130771984;
			
			// aapt resource value: 0x7f01000f
			public const int visual_feedback_corner_radius_in_dp = 2130771983;
			
			// aapt resource value: 0x7f01000e
			public const int visual_feedback_fill_color = 2130771982;
			
			// aapt resource value: 0x7f010012
			public const int visual_feedback_redraw_timeout = 2130771986;
			
			// aapt resource value: 0x7f01000c
			public const int visual_feedback_stroke_color = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int visual_feedback_stroke_width_in_dp = 2130771981;
			
			// aapt resource value: 0x7f01000b
			public const int visual_feedback_style = 2130771979;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int anyline_logo_white = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int flash_control_background = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int flash_icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int flash_icon_auto = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int flash_icon_off = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Icon = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05001c
			public const int AnylineScanView = 2131034140;
			
			// aapt resource value: 0x7f050019
			public const int any = 2131034137;
			
			// aapt resource value: 0x7f050012
			public const int auto = 2131034130;
			
			// aapt resource value: 0x7f05001a
			public const int back = 2131034138;
			
			// aapt resource value: 0x7f050004
			public const int blink = 2131034116;
			
			// aapt resource value: 0x7f05000b
			public const int bottom = 2131034123;
			
			// aapt resource value: 0x7f05000e
			public const int bottom_half = 2131034126;
			
			// aapt resource value: 0x7f050015
			public const int bottom_left = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int bottom_right = 2131034134;
			
			// aapt resource value: 0x7f05000f
			public const int center = 2131034127;
			
			// aapt resource value: 0x7f05000c
			public const int center_vertically = 2131034124;
			
			// aapt resource value: 0x7f050000
			public const int contour_point = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int contour_rect = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int contour_underline = 2131034114;
			
			// aapt resource value: 0x7f05001b
			public const int front = 2131034139;
			
			// aapt resource value: 0x7f050011
			public const int image = 2131034129;
			
			// aapt resource value: 0x7f050005
			public const int kitt = 2131034117;
			
			// aapt resource value: 0x7f050013
			public const int manual = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int none = 2131034132;
			
			// aapt resource value: 0x7f050006
			public const int pulse = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int pulse_random = 2131034119;
			
			// aapt resource value: 0x7f050003
			public const int rect = 2131034115;
			
			// aapt resource value: 0x7f050008
			public const int resize = 2131034120;
			
			// aapt resource value: 0x7f05000d
			public const int top = 2131034125;
			
			// aapt resource value: 0x7f050010
			public const int top_half = 2131034128;
			
			// aapt resource value: 0x7f050017
			public const int top_left = 2131034135;
			
			// aapt resource value: 0x7f050018
			public const int top_right = 2131034136;
			
			// aapt resource value: 0x7f050009
			public const int traverse_multi = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int traverse_single = 2131034122;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040004
			public const int ApplicationName = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int Hello = 2130968579;
			
			// aapt resource value: 0x7f040000
			public const int flash_auto = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int flash_off = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int flash_on = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] AnylineBaseModuleView = new int[] {
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986};
			
			// aapt resource value: 0
			public const int AnylineBaseModuleView_beep_on_result = 0;
			
			// aapt resource value: 2
			public const int AnylineBaseModuleView_blink_animation_on_result = 2;
			
			// aapt resource value: 3
			public const int AnylineBaseModuleView_cancel_on_result = 3;
			
			// aapt resource value: 4
			public const int AnylineBaseModuleView_cutout_feedback_stroke_color = 4;
			
			// aapt resource value: 1
			public const int AnylineBaseModuleView_vibrate_on_result = 1;
			
			// aapt resource value: 11
			public const int AnylineBaseModuleView_visual_feedback_animation_duration = 11;
			
			// aapt resource value: 10
			public const int AnylineBaseModuleView_visual_feedback_animation_style = 10;
			
			// aapt resource value: 9
			public const int AnylineBaseModuleView_visual_feedback_corner_radius_in_dp = 9;
			
			// aapt resource value: 8
			public const int AnylineBaseModuleView_visual_feedback_fill_color = 8;
			
			// aapt resource value: 12
			public const int AnylineBaseModuleView_visual_feedback_redraw_timeout = 12;
			
			// aapt resource value: 6
			public const int AnylineBaseModuleView_visual_feedback_stroke_color = 6;
			
			// aapt resource value: 7
			public const int AnylineBaseModuleView_visual_feedback_stroke_width_in_dp = 7;
			
			// aapt resource value: 5
			public const int AnylineBaseModuleView_visual_feedback_style = 5;
			
			public static int[] AnylineCameraView = new int[] {
					2130771968,
					2130771969,
					2130771972,
					2130771973,
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991};
			
			// aapt resource value: 4
			public const int AnylineCameraView_crop_gravity = 4;
			
			// aapt resource value: 0
			public const int AnylineCameraView_overlay_drawable = 0;
			
			// aapt resource value: 6
			public const int AnylineCameraView_overlay_height = 6;
			
			// aapt resource value: 1
			public const int AnylineCameraView_overlay_outside_color = 1;
			
			// aapt resource value: 5
			public const int AnylineCameraView_overlay_width = 5;
			
			// aapt resource value: 7
			public const int AnylineCameraView_overlay_x = 7;
			
			// aapt resource value: 8
			public const int AnylineCameraView_overlay_y = 8;
			
			// aapt resource value: 2
			public const int AnylineCameraView_preferred_preview_height = 2;
			
			// aapt resource value: 3
			public const int AnylineCameraView_preferred_preview_width = 3;
			
			public static int[] AnylineView = new int[] {
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771992,
					2130771993,
					2130771994,
					2130771995,
					2130771996,
					2130771997,
					2130771998,
					2130771999,
					2130772000,
					2130772001,
					2130772002,
					2130772003,
					2130772004,
					2130772005,
					2130772006,
					2130772007,
					2130772008,
					2130772009,
					2130772010,
					2130772011,
					2130772012,
					2130772013,
					2130772014};
			
			// aapt resource value: 4
			public const int AnylineView_cutout_alignment = 4;
			
			// aapt resource value: 19
			public const int AnylineView_cutout_crop_offset_x = 19;
			
			// aapt resource value: 20
			public const int AnylineView_cutout_crop_offset_y = 20;
			
			// aapt resource value: 17
			public const int AnylineView_cutout_crop_padding_x = 17;
			
			// aapt resource value: 18
			public const int AnylineView_cutout_crop_padding_y = 18;
			
			// aapt resource value: 16
			public const int AnylineView_cutout_drawable = 16;
			
			// aapt resource value: 7
			public const int AnylineView_cutout_max_height_percent = 7;
			
			// aapt resource value: 6
			public const int AnylineView_cutout_max_width_percent = 6;
			
			// aapt resource value: 8
			public const int AnylineView_cutout_offset_x = 8;
			
			// aapt resource value: 9
			public const int AnylineView_cutout_offset_y = 9;
			
			// aapt resource value: 21
			public const int AnylineView_cutout_outside_color = 21;
			
			// aapt resource value: 14
			public const int AnylineView_cutout_ratio_from_size_height = 14;
			
			// aapt resource value: 13
			public const int AnylineView_cutout_ratio_from_size_width = 13;
			
			// aapt resource value: 15
			public const int AnylineView_cutout_rect_corner_radius_in_dp = 15;
			
			// aapt resource value: 12
			public const int AnylineView_cutout_stroke_color = 12;
			
			// aapt resource value: 11
			public const int AnylineView_cutout_stroke_width_in_dp = 11;
			
			// aapt resource value: 10
			public const int AnylineView_cutout_style = 10;
			
			// aapt resource value: 5
			public const int AnylineView_cutout_width = 5;
			
			// aapt resource value: 23
			public const int AnylineView_flash_alignment = 23;
			
			// aapt resource value: 26
			public const int AnylineView_flash_image_auto = 26;
			
			// aapt resource value: 25
			public const int AnylineView_flash_image_off = 25;
			
			// aapt resource value: 24
			public const int AnylineView_flash_image_on = 24;
			
			// aapt resource value: 22
			public const int AnylineView_flash_mode = 22;
			
			// aapt resource value: 0
			public const int AnylineView_preferred_picture_height = 0;
			
			// aapt resource value: 1
			public const int AnylineView_preferred_picture_width = 1;
			
			// aapt resource value: 2
			public const int AnylineView_preferred_preview_height = 2;
			
			// aapt resource value: 3
			public const int AnylineView_preferred_preview_width = 3;
			
			public static int[] CameraBridgeViewBase = new int[] {
					2130772015,
					2130772016};
			
			// aapt resource value: 1
			public const int CameraBridgeViewBase_camera_id = 1;
			
			// aapt resource value: 0
			public const int CameraBridgeViewBase_show_fps = 0;
			
			public static int[] OverlayView = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public const int OverlayView_overlay_drawable = 0;
			
			// aapt resource value: 1
			public const int OverlayView_overlay_outside_color = 1;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
